name = "akeneo-cloudflare-connector"
main = "src/index.js"
compatibility_date = "2024-06-20"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
id = "20a731711d864a9687fcdf5eb98fa484"
binding = "CATALOG_NAVIGATION_CACHE"

[[kv_namespaces]]
id = "50319789a6f0498285717599ff96a8c7"
binding = "CATEGORY_CACHE"

[[kv_namespaces]]
id = "129e33beab4447ab82531f36959648ce"
binding = "PRODUCT_CACHE"

[vars]
AKENEO_CLIENT_ID = "5_4783t5p173qc80c4w4cgwggos0ws0kogkkgw04cs8080os4kw4"
AKENEO_HOST = "russellkmoore.ngrok.io"
AKENEO_PASSWORD = "6070e675f"
AKENEO_SECRET = "1yzu9axvynz4ksskw8ckk0csokscg0o4cs4kco4w0o4o0k0g04"
AKENEO_USERNAME = "cloudflare_1314"
