name = "akeneo-cloudflare-connector"
main = "src/index.js"
compatibility_date = "2024-06-20"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
id = "20a731711d864a9687fcdf5eb98fa484"
binding = "akeneo_catalog"

[[kv_namespaces]]
id = "50319789a6f0498285717599ff96a8c7"
binding = "akeneo_categories"

[[kv_namespaces]]
id = "129e33beab4447ab82531f36959648ce"
binding = "akeneo_products"

[vars]
AKENEO_CLIENT_ID = "5_u9kio095vgg0wsg0g4gk8k0wk0cc4ow8occ8wwwkgkcosw0g8"
AKENEO_HOST = "51711784b681.ngrok.app"
AKENEO_PASSWORD = "6f5e706c5"
AKENEO_SECRET = "4aimwe4vqnmskg40ok0wgwg00skgg4ggoc04gcw8kwgwgg48s4"
AKENEO_USERNAME = "cloudflare_9112"
